web/home_energy/urls.py
from django.urls import path

from . import views

app_name = 'home-energy'
urlpatterns = [
    # ex: /home-energy/
    path('', views.usage, name='usage'),
    # ex: /home-energy/usage.html
    path('usage.html', views.usage, name='usage'),

    # ex: /home-energy/latest_usage
    # ex: /home-energy/latest_usage/
    path('latest_usage', views.latest_usage, name='latest_usage'),
    path('latest_usage/', views.latest_usage, name='latest_usage'),

    # ex: /home-energy/detailed_usage
    # ex: /home-energy/detailed_usage/
    path('detailed_usage', views.detailed_usage, name='detailed_usage'),
    path('detailed_usage/', views.detailed_usage, name='detailed_usage'),

    # ex: /home-energy/total_usage
    # ex: /home-energy/total_usage
    path('total_usage', views.total_usage, name='total_usage'),
    path('total_usage/', views.total_usage, name='total_usage'),

    # ex: /home-energy/total_cost
    # ex: /home-energy/total_cost
    path('total_cost', views.total_cost, name='total_cost'),
    path('total_cost/', views.total_cost, name='total_cost'),

    # ex: /home-energy/prices.html
    path('prices.html', views.prices, name='prices'),

    # ex: /home-energy/get_all_prices
    # ex: /home-energy/get_all_prices/
    path('get_all_prices', views.get_all_prices, name='get_all_prices'),

    path('add_price', views.add_price, name='add_price'),
    path('modify_price', views.modify_price, name='modify_price'),
    path('remove_price', views.remove_price, name='remove_price'),

    # ex: /home-energy/debug/p1-reader.html
    path('debug/p1-reader.html', views.debug_p1_reader, name='debug_p1_reader'),
]

web/home_portal/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

if not settings.configured:
    settings.configure(FEATURE_HEATING_APP=1)
    settings.configure(FEATURE_VENT_APP=1)

urlpatterns = [
    path('home-energy/', include('home_energy.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

if settings.FEATURE_HEATING_APP:
    urlpatterns.append(path('home-heating/', include('home_heating.urls')))

if settings.FEATURE_VENT_APP:
    urlpatterns.append(path('home-vent/', include('home_vent.urls')))

web/home_vent/urls.py
from django.urls import path

from . import views

app_name = 'home-vent'
urlpatterns = [
    # ex: /home-vent/
    # ex: /home-vent/main.html
    path('', views.main, name='main'),
    path('main.html', views.main, name='main'),

    # ex: /home-vent/get/<field>
    path('get/<str:field>', views.get, name='get'),

    # ex: /home-vent/getAll
    # ex: /home-vent/getAll/
    path('getAll', views.getAll, name='getAll'),
    path('getAll/', views.getAll, name='getAll'),

    # ex: /home-vent/action/<action>
    path('action/<str:action>', views.action, name='action')
]

web/home_energy/forms.py
from django import forms
from django.core.exceptions import ValidationError

class AddPriceForm(forms.Form):
    starttime = forms.DateField(required=True,   widget=forms.TextInput(attrs={'type': 'date'}))
    down_high = forms.FloatField(required=False, widget=forms.TextInput(attrs={'step': ''}))
    down_low  = forms.FloatField(required=False, widget=forms.TextInput(attrs={'step': ''}))
    up_high   = forms.FloatField(required=False, widget=forms.TextInput(attrs={'step': ''}))
    up_low    = forms.FloatField(required=False, widget=forms.TextInput(attrs={'step': ''}))
    peak_down = forms.FloatField(required=False, widget=forms.TextInput(attrs={'step': ''}))
    gas       = forms.FloatField(required=False, widget=forms.TextInput(attrs={'step': ''}))

    def clean(self):
        cleaned_data = super().clean()
        down_high = cleaned_data.get("down_high")
        down_low  = cleaned_data.get("down_low")
        up_high   = cleaned_data.get("up_high")
        up_low    = cleaned_data.get("up_low")
        peak_down = cleaned_data.get("peak_down")
        gas       = cleaned_data.get("gas")

        if (not down_high and
            not down_low and
            not up_high and
            not up_low and
            not peak_down and
            not gas):
            # All price fields are empty
            raise ValidationError("At least one price should be filled in.")

class ModifyPriceForm(AddPriceForm):
    id = forms.CharField(required=True, widget=forms.HiddenInput())

class RemovePriceForm(forms.Form):
    id = forms.CharField(required=True, widget=forms.HiddenInput())

class GetTotalsForm(forms.Form):
    startdate = forms.DateField(required=True, widget=forms.TextInput(attrs={'type': 'date'}))
    enddate   = forms.DateField(required=True, widget=forms.TextInput(attrs={'type': 'date'}))
    mode      = forms.IntegerField(required=True, min_value=1, max_value=4)

    def clean(self):
        cleaned_data = super().clean()
        startdate = cleaned_data.get("startdate")
        enddate  = cleaned_data.get("enddate")

        if startdate is None:
            raise ValidationError("Invalid startdate.")

        if enddate is None:
            raise ValidationError("Invalid enddate.")

        if (enddate < startdate):
            raise ValidationError("Startdate must be before enddate.")

web/home_energy/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse

from home_energy.forms import *

from home_energy.view import energy_common as ec
from home_energy.view import usage as u
from home_energy.view import p1_reader_debug
from home_energy.view import prices as pr
from home_energy.view import cost

import json

@login_required
def usage(request):
    return render(request, 'home_energy/usage.html')

@login_required
def latest_usage(request):
    return HttpResponse(json.dumps(u.get_latest_usage()), content_type="application/json")

@login_required
def detailed_usage(request):
    date = request.GET.get('date', '')
    mode = request.GET.get('mode', 1)
    detailed_usage = u.get_detailed_usage(date, mode)
    return HttpResponse(json.dumps(detailed_usage), content_type="application/json")

@login_required
def total_usage(request):
    form = GetTotalsForm(request.GET)
    if form.is_valid():
        starttime = ec.get_epoch_time_s(form.cleaned_data['startdate'])
        endtime = ec.get_epoch_time_s(form.cleaned_data['enddate'] + datetime.timedelta(days=1))
        mode = form.cleaned_data['mode']
        total_usage = u.get_total_usage(starttime, endtime, mode)
    else:
        return HttpResponse(json.dumps({"errors" : form.errors}), content_type="application/json")
    return HttpResponse(json.dumps(total_usage), content_type="application/json")

@login_required
def total_cost(request):
    form = GetTotalsForm(request.GET)
    if form.is_valid():
        starttime = ec.get_epoch_time_s(form.cleaned_data['startdate'])
        endtime = ec.get_epoch_time_s(form.cleaned_data['enddate'] + datetime.timedelta(days=1))
        mode = form.cleaned_data['mode']
        total_costs = cost.get_total_costs(starttime, endtime, mode)
    else:
        return HttpResponse(json.dumps({"errors" : form.errors}), content_type="application/json")
    return HttpResponse(json.dumps(total_costs), content_type="application/json")


def get_modify_price_forms():
    prices = pr.get_all_prices_reversed()
    modify_price_forms = []
    for price in prices:
        epoch = ec.get_datetime_from_epoch_in_s(int(price['starttime']))
        price['starttime'] = ec.format_epoch(epoch, "%Y-%m-%d")
        modify_price_forms.append(ModifyPriceForm(price))
    return modify_price_forms

@login_required
def prices(request):
    context = {
        'add_price_form': AddPriceForm(),
        'modify_price_forms' : get_modify_price_forms(),
    }
    return render(request, 'home_energy/prices.html', context)

@login_required
def get_all_prices(request):
    return HttpResponse(json.dumps(pr.get_all_prices_reversed()), content_type="application/json")

@login_required
def add_price(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse('home-energy:prices'))

    form = AddPriceForm(request.POST)

    if form.is_valid():
        starttime = form.cleaned_data['starttime']
        rates = {k: v for k, v in form.cleaned_data.items() if k != 'starttime' and v is not None}
        rv = pr.add_price(ec.get_epoch_time_s(starttime), rates)
        if rv != -1:
            return HttpResponseRedirect(reverse('home-energy:prices'))
        else:
            form.add_error(None, 'Failed to add price.')

    context = {
        'add_price_form': form,
        'modify_price_forms' : get_modify_price_forms(),
    }

    return render(request, 'home_energy/prices.html', context)

@login_required
def modify_price(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse('home-energy:prices'))

    form = ModifyPriceForm(request.POST)

    if form.is_valid():
        starttime = form.cleaned_data['starttime']
        rates = {k: v for k, v in form.cleaned_data.items() if k != 'starttime' and k != 'id' and v is not None}
        rv = pr.modify_price(form.cleaned_data['id'], ec.get_epoch_time_s(starttime), rates)
        if rv != -1:
            return HttpResponseRedirect(reverse('home-energy:prices'))
        else:
            form.add_error(None, 'Failed to modify price.')

    #replace the empty form in the list with the one with errors in it
    modify_price_forms = get_modify_price_forms()
    for i in range(len(modify_price_forms)):
        f = modify_price_forms[i]
        if f.is_valid() and f.cleaned_data['id'] == form.cleaned_data['id']:
            modify_price_forms[i] = form
            break

    context = {
        'add_price_form': AddPriceForm(),
        'modify_price_forms' : modify_price_forms,
    }

    return render(request, 'home_energy/prices.html', context)

@login_required
def remove_price(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse('home-energy:prices'))

    form = RemovePriceForm(request.POST)

    if form.is_valid():
        pr.remove_price(form.cleaned_data['id'])

    return HttpResponseRedirect(reverse('home-energy:prices'))

@login_required
def debug_p1_reader(request):
    context = {'debug_entries': p1_reader_debug.get_debug_entries()}
    return render(request, 'home_energy/debug/p1-reader.html', context)

web/home_energy/templates/home_energy/modify_price_form.html
        <div id="{{ price.id }}" class="modify_price_div">
            <form action="{% url 'home-energy:modify_price' %}" method="post" class="modify_price_form">
                {% csrf_token %}
                {{ form.id }}
                {% include "home_energy/price_input_table.html" with form=form %}
                <button type="submit">
                    <i class="bi bi-pencil-square"></i> Save
                </button>
            </form>
            <form action="{% url 'home-energy:remove_price' %}" method="post" class="remove_price_form">
                {% csrf_token %}
                {{ form.id }}
                <button type="submit" onclick="return confirm('Remove this price?');">
                    <i class="bi bi-trash"></i> Delete
                </button>
            </form>
        </div>

web/home_energy/templates/home_energy/price_input_table.html
                {{ form.non_field_errors }}
                {{ form.starttime.errors }}
                {{ form.down_high.errors }}
                {{ form.down_low.errors }}
                {{ form.up_high.errors }}
                {{ form.up_low.errors }}
                {{ form.peak_down.errors }}
                {% if FEATURE_GAS %}
                {{ form.gas.errors }}
                {% endif %}
                <div class="starttime_div">
                    {{ form.starttime }}
                </div>
                <table class="form_input_table">
                    <tr>
                        <td><label for="{{ form.down_high.id_for_label }}"><i class="bi bi-sun"></i> Down</label></td>
                        <td>{{ form.down_high }}</td>
                        <td><label for="{{ form.down_low.id_for_label }}"> <i class="bi bi-moon"></i>Down</label></td>
                        <td>{{ form.down_low }}</td>
                    </tr>
                    <tr>
                        <td><label for="{{ form.up_high.id_for_label }}"><i class="bi bi-sun"></i> Up</label></td>
                        <td>{{ form.up_high }}</td>
                        <td><label for="{{ form.up_low.id_for_label }}"> <i class="bi bi-moon"></i> Up</label></td>
                        <td>{{ form.up_low }}</td>
                    </tr>
                    <tr>
                        <td><label for="{{ form.peak_down.id_for_label }}"><i class="bi bi-arrow-up-square"></i> Peak (Kw/year)</label></td>
                        <td>{{ form.peak_down }}</td>
                        <td>{% if FEATURE_GAS %}<label for="{{ form.gas.id_for_label }}"><i class="bi bi-fire"></i> Gas</label>{% endif %}</td>
                        <td>{% if FEATURE_GAS %}{{ form.gas }}{% endif %}</td>
                    </tr>
                </table>

web/home_energy/templates/home_energy/prices.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home Energy - Prices</title>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <link rel="manifest" href="{% static 'home_energy/manifest.json' %}" />
    <link rel="icon" href="{% static 'home_energy/favicon.ico' %}" sizes="any">
    <link rel="apple-touch-icon" href="{% static 'home_energy/apple-touch-icon.png' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'home_energy/prices.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <h1>Prices</h1>
    </br>
    <a href="{% url 'home-energy:usage' %}" class="btn btn-primary"><i class="bi bi-lightning"></i> View Usage</a>
    <br/>
    <br/>
    <div id="add_price_div" class="add_price_div">
        <form action="{% url 'home-energy:add_price' %}" method="post">
            {% csrf_token %}
            {% include "home_energy/price_input_table.html" with form=add_price_form %}
            <button type="submit">
                <i class="bi bi-plus-square"></i> Add
            </button>
        </form>
    </div>
    <br/>
    <br/>
    <div id="prices_div">
    {% for modify_price_form in modify_price_forms %}
        {% include "home_energy/modify_price_form.html" with form=modify_price_form %}
    {% endfor %}
    </div>
</body>
</html>